services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: constructflow_file
    env_file:
      - .env
    environment:
      - APP_SECRET=${APP_SECRET}
      - CONFIG_PATH=configs/docker.yaml
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=constructflow
      - SSL_MODE=disable
      - GRPC_KEY = 88XU6LYFGeT8RGgX/3Tp1C1K1a8XwHUi9BCKsx04WwA=
    depends_on:
      - postgres
    # Убираем volumes, чтобы не затирать содержимое /app в контейнере
    # volumes:
    #   - .:/app
    ports:
      - "${APP_PORT:-8081}:8080"
      - "${GRPC_PORT-50051}:50051"
    networks:
      - app-network
    restart: always

  postgres:
    image: postgres
    container_name: postgres_file
    env_file:
      - .env
    environment:
      - POSTGRES_DB=constructflow_file
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5434}:5432"
    networks:
      - app-network
    restart: always

  migrator_file:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: migrator_file
    env_file:
      - .env
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=constructflow_file
    depends_on:
      - postgres
    networks:
      - app-network
    command: ["/app/migrator", "-reset", "-migrate", "-seed"]
    restart: "no"

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address :9001
    networks:
      - app-network
    restart: always


# сейчас тут костыль и нужно прописывать это: docker network create -d bridge app-network
networks:
  app-network:
    external: true

volumes:
  pgdata:
  minio_data: 
