services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: constructflow
    environment:
      - APP_SECRET=${APP_SECRET}
      - CONFIG_PATH=configs/docker.yaml
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=constructflow
      - SSL_MODE=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - .:/app
    restart: always

    

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=constructflow
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  pgdata: