version: "3"
tasks:
  run:
    desc: "runs main.go file"
    cmds:
      - go run cmd/api/main.go
  seeddb:
    desc: "applies migrations"
    cmds:
      - go run cmd/migrator/main.go -reset -migrate -seed
  build:
    desc: "builds docker-compose file"
    cmds:
      - docker-compose down
      - docker-compose up --build -d
  composedown:
    desc: "stops containers"
    cmds:
      - docker-compose down -v
  swag:
    desc: "initializes swagger doc"
    cmds:
      - swag init -g cmd/api/main.go --parseDependency --parseInternal