version: "3"
tasks:
  run:
    desc: "runs main.go file"
    cmds:
      - go run cmd/api/main.go
  build:
    desc: "builds docker-compose file"
    cmds:
      - docker-compose down
      - docker-compose up --build -d
  composedown:
    desc: "stops containers"
    cmds:
      - docker-compose down