services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: constructflow_file
    env_file:
      - .env
    environment:
      - APP_SECRET=${APP_SECRET}
      - CONFIG_PATH=configs/docker.yaml
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=constructflow
      - SSL_MODE=disable
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "${APP_PORT:-8081}:8080"
      - "${GRPC_PORT-50051}:50051"
    networks:
      - app-network
    restart: always

  postgres:
    image: postgres
    container_name: postgres_file
    env_file:
      - .env
    environment:
      - POSTGRES_DB=constructflow_file
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5434}:5432"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
