version: "3"
tasks:
  run:
    desc: "runs main.go file"
    cmds:
      - go run cmd/main.go
  build:
    desc: "builds docker-compose file"
    cmds:
      - docker-compose down -v
      - docker-compose up --build -d