services:

  db_postgres:
    image: postgres:16
    container_name: db_postgres
    env_file:
      - .env_prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "root"]
    
  constructflow_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: constructflow_app
    env_file:
      - .env_prod
    command: sh -c "go run cmd/api/main.go"
    ports:
      - "8080:8080"
    volumes:
      - app:/app
    networks:
      - app-network
    restart: always
    depends_on:
      db_postgres:
          condition: service_healthy

networks:
  app-network:

volumes:
  app:
  pgdata:
