definitions:
  domain.DirectoryResponse:
    description: Информация о директории
    properties:
      files:
        items:
          $ref: '#/definitions/domain.FileResponse'
        type: array
      id:
        type: integer
      name_folder:
        type: string
      parent_path_id:
        type: integer
      status:
        type: string
    type: object
  domain.ErrorResponse:
    description: Структура ошибки API
    properties:
      error:
        properties:
          code:
            example: INVALID_REQUEST
            type: string
          message:
            example: Invalid request body
            type: string
        type: object
    type: object
  domain.FileResponse:
    description: Информация о файле
    properties:
      directory_id:
        type: integer
      id:
        type: integer
      name_file:
        type: string
      status:
        type: string
    type: object
  domain.GetCurrentUserResponse:
    description: Информация о пользователе
    properties:
      id:
        type: integer
      login:
        type: string
      role:
        type: string
    type: object
  domain.GetFileTreeResponse:
    description: Структура ответа для дерева файлов
    properties:
      data:
        items:
          $ref: '#/definitions/domain.DirectoryResponse'
        type: array
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Возвращает JWT токен при успешной аутентификации
      parameters:
      - description: Логин для входа
        in: body
        name: login
        required: true
        schema:
          type: string
      - description: Пароль для входа
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Токен доступа
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Неверные учетные данные
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Аутентификация пользователя
      tags:
      - auth
  /api/v1/auth/me:
    get:
      description: Возвращает информацию о пользователе на основе JWT токена
      produces:
      - application/json
      responses:
        "200":
          description: Информация о пользователе
          schema:
            $ref: '#/definitions/domain.GetCurrentUserResponse'
        "401":
          description: Не авторизован
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - JWT: []
      summary: Получение информации о текущем пользователе
      tags:
      - auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Регистрирует нового пользователя и возвращает его ID
      parameters:
      - description: Логин пользователя
        in: body
        name: login
        required: true
        schema:
          type: string
      - description: Пароль пользователя
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: ID роли, назначенной пользователю
        in: body
        name: role_id
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "201":
          description: ID созданного пользователя
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: Роль не найдена
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "409":
          description: Пользователь с таким логином уже существует
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Регистрация нового пользователя
      tags:
      - auth
  /api/v1/auth/role:
    post:
      consumes:
      - application/json
      description: Регистрирует новую роль и возвращает её ID
      parameters:
      - description: Название роли
        in: body
        name: role_name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: ID созданной роли
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "409":
          description: Роль с таким названием уже существует
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Регистрация новой роли
      tags:
      - auth
  /api/v1/directories:
    delete:
      consumes:
      - application/json
      description: Удаляет директорию и все её связи
      parameters:
      - description: ID директории для удаления
        in: body
        name: directory_id
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Сообщение об успехе
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Не авторизован
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "403":
          description: Нет доступа
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Внутренняя ошибка
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - JWT: []
      summary: Удалить директорию
      tags:
      - directories
    get:
      description: Возвращает структуру файлов и директорий для пользователя
      parameters:
      - description: Фильтр архивных элементов
        in: body
        name: is_archive
        schema:
          type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.GetFileTreeResponse'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Не авторизован
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Внутренняя ошибка
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - JWT: []
      summary: Получить дерево файлов и директорий
      tags:
      - directories
  /api/v1/directories/upload:
    post:
      consumes:
      - application/json
      description: Создает директорию и связывает её с пользователем
      parameters:
      - description: ID родительской директории (null для корня)
        in: body
        name: parent_path_id
        required: true
        schema:
          type: integer
      - description: Название директории
        in: body
        name: name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: ID созданной директории
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Не авторизован
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "403":
          description: Нет доступа
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Внутренняя ошибка
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - JWT: []
      summary: Создать новую директорию
      tags:
      - directories
  /api/v1/files:
    delete:
      consumes:
      - application/json
      description: Удаляет файл и все его связи
      parameters:
      - description: ID файла для удаления
        in: body
        name: file_id
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Сообщение об успехе
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Не авторизован
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "403":
          description: Нет доступа
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: Файл не найден
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Внутренняя ошибка
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - JWT: []
      summary: Удалить файл
      tags:
      - files
  /api/v1/files/{file_id}:
    get:
      description: Возвращает детали файла по его ID
      parameters:
      - description: ID файла
        in: path
        name: file_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.FileResponse'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Не авторизован
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "403":
          description: Нет доступа
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: Файл не найден
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Внутренняя ошибка
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - JWT: []
      summary: Получить информацию о файле
      tags:
      - files
  /api/v1/files/upload:
    post:
      consumes:
      - application/json
      description: Создает файл и связывает его с пользователем
      parameters:
      - description: ID директории
        in: body
        name: directory_id
        required: true
        schema:
          type: integer
      - description: Имя файла
        in: body
        name: name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: ID созданного файла
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Не авторизован
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "403":
          description: Нет доступа
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Внутренняя ошибка
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - JWT: []
      summary: Загрузить файл
      tags:
      - files
swagger: "2.0"
