env: "local"
storage_path: "./data/storage.db"
token_ttl: 1h
http_server:
  address: "localhost:8091"
  timeout: 4s
  idle_timeout: 60s

grpc_server:
  address: ":50051"
  timeout: 4s
  idle_timeout: 60s

database:
  host: "host.docker.internal"
  port: 5434
  name: "constructflow_file"
  ssl_mode: "disable"