env: "local"
storage_path: "./data/storage.db"
token_ttl: 1h
http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s

database:
  host: "host.docker.internal"
  port: 5432
  user: "snowwy"
  password: "megaballsgaming"
  name: "constructflow"
  ssl_mode: "disable"